# Northeast Assessment Config Options
base_path: "/storage/data/projects/rci/data/assessments/Northeast_2025/App_Files/"

category_order:
  - Precipitation_Indices
  - Temperature_Indices
  - Drought_Indices
  - Return_Levels
  - Return_Period_Changes

region_order:
  - Northeast
  - Chetwynd
  - Dawson_Creek
  - Doig_River_FN
  - Fort_Nelson
  - Fort_St_John
  - Northern_Rockies_Municipality
  - Peace_Highlands
  - Peace_Lowlands
  - Peace_Regional_District
  - Tumbler_Ridge
  - West_Moberly_FN